bot_usr = "" # bot's username - without u/
bot_pwd = "" # bot's password
bot_secret = "" # secret, longer string from reddit.com/prefs/apps
bot_id = "" # id, shorter string from reddit.com/prefs/apps
bot_agent = "Word Counter made by u/m4rzus" # Description
bot_subreddit = ["learnpython", "redditdev"] # Subreddits the bot is interested in - without r/
bot_redditor = "" # Redditor bot will be looking at - without u/
bot_send_to = "" # Redditor bot will send the summary to - probably the same as bot_redditor - without u/
bot_post_age_hours = 24 # Bot will check only posts older than this amount of hours
bot_min_count = 2 # Min. number of occurrences of a word to include it in the summary
