bot_usr = "" # username
bot_pwd = "" # password
bot_secret = "" # secret, longer string from reddit.com/prefs/apps
bot_id = "" # id, shorter string from reddit.com/prefs/apps
bot_agent = "Comment Vote System made by u/m4rzus" # Description
bot_subreddit = "" # The subreddit the bot is interested in
bot_flair = "" # Bot will comment only on posts with this flair, leave blank ("") for all posts
bot_choices = ["Shitpost", "Good meme", "Perfection"] # Choices for voters
bot_update = 2 # Bot will update every relevant post after this number of HOURS
bot_max_age = 7 # Bot will not look at posts older than this number of DAYS
